# Generated by Django 4.2.3 on 2023-07-16 23:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="City_House_Price",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("city", models.CharField(max_length=60)),
                ("state", models.CharField(max_length=60)),
                ("average_price", models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name="Avocado_Price",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("average_price", models.FloatField()),
                ("total_volume", models.FloatField()),
                ("avocado_4046", models.FloatField()),
                ("avocado_4225", models.FloatField()),
                ("avocado_4770", models.FloatField()),
                ("total_bags", models.FloatField()),
                ("small_bags", models.FloatField()),
                ("large_bags", models.FloatField()),
                ("xlarge_bags", models.FloatField()),
                ("avocado_type", models.CharField(max_length=60)),
                (
                    "city",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="website.city_house_price",
                    ),
                ),
            ],
        ),
    ]
